### ISSUE TITLE
la CD avec cloud run

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [Sometimes-Useful/the-cleavage-game#15]
* [ ] dockerize app, caddy reverse proxy for local docjker-compose
* [ ] helm chart
* [ ] add CICD Pipeline (will be Circle CI)
* [ ] pipeline must : 
  * run all linters (Dockerfile etc..)
  * run test
  * build the app
  * build the Docker image and push it to github
* deploy to a Kubernetes : 
  * [ ] on private kubernetes cluster, fluxcd and a github repo as source of truth (eventually with a DynDNS and/or a tunnel to a VM with public IP)
  * [ ] on Azure AKS kubernetes with OVH domain names Kubernetes External DNS

**Comment by Jean-Baptiste-Lasselle** [comment]
* deploy to GCP with docker push : https://cloud.google.com/run/docs/deploying

**Comment by Jean-Baptiste-Lasselle** [comment]
https://www.pulumi.com/registry/packages/gcp-global-cloudrun/

**Comment by bbohec** [comment]
CI/CD proposal refused.
Current CI/CD updated with :
- GitHub Actions as CI/CD Pipeline triggered on push/PR
- Testing Workflows
- Build & Deploy workflow with:
  - Build docker image from docker file and push it to GCP container registry
  - GCP Cloud Run based deployment
  
Continous improvment are expected on CI/CD.

Current improvements that may reduce total pipeline execution time : workflows split & artefacts/caching.
